### ISSUE TITLE
question: How can i use the Topic and Trend Analysis Solution

### ISSUE THREAD

**Issue by Warra07** [IntelLabs/nlp-architect#187]
I don't find any example on its usage, and can we apply our own trained model on the np extraction task ?

**Comment by peteriz** [comment]
Hi @Warra07, more details on Trends and topic analysis can be found on our docs website [here](http://nlp_architect.nervanasys.com/trend_analysis.html)
You can apply your own model, however it might require a bit of modification of the solution code (to integrate your model).
