### ISSUE TITLE
How to improve bist model accuracy? :Bistmodel

### ISSUE THREAD

**Issue by ravishpankar** [IntelLabs/nlp-architect#188]
I'm using spacybistparser with my own spacy and bist model trained using universal dependencies v2.0 dataset. My training follows the doc. I want to improve the accuracy of bistmodel. Currently, with default parameters, I train the bist model for 20iterations. The evaluation uas score is 87.8 percent. How can I improve it to 93.8 as mentioned in the docs? Is it possible with this english ud 2.0 dataset? Please help.

**Comment by ravishpankar** [comment]
Any answer?

**Comment by peteriz** [comment]
@danielkorat, do you might have an answer?

**Comment by ravishpankar** [comment]
@peteriz, thank you for requesting @danielkorat. This is very important to my project. I would like little lesser errors in parsing job descriptions. I guess improving the accuracy would result in fewer parsing errors. Please clarify this one too. I can always give it a try after improving the accuracy.

**Comment by danielkorat** [comment]
Hi @ravishpankar, sorry for the delayed response.
93.8 UAS is the score reported in the [original paper](https://transacl.org/ojs/index.php/tacl/article/viewFile/885/198) and original [code implementation](https://github.com/elikip/bist-parser). As mentioned there, this result is reported on the Penn TreeBank Dataset (Stanford Dependencies).
Training on a different dataset might yield different results.

**Comment by ravishpankar** [comment]
Hi @danielkorat, Thanks a lot for answering. I understand that universal dependencies 2.0 en dataset is different from Penn tree bank dataset which is based upon Stanford dependency relations. Now the question is how did you train the bistmodel with Penn tree bank dataset to create the pretrained model for spacybistparser. Is it with the default parameters or something else? Any help will be greatly appreciated. Thank you.

**Comment by danielkorat** [comment]
Hi @ravishpankar 
From what I recall, I used the default parameters.
