### ISSUE TITLE
url for quant BERT config.json is invalid

### ISSUE THREAD

**Issue by A-Rain** [IntelLabs/nlp-architect#193]
hello, I come from [this issue](https://github.com/NervanaSystems/nlp-architect/issues/163. And now I'm using the newest version of nlp-architect, while the url 
```
https://nlp-architect-data.s3-us-west-2.amazonaws.com/models/transformers/bert-base-uncased.json
```
is still invalid. Could you please fix the server and provide new url as soon as possible?

thanks

**Comment by peteriz** [comment]
Please use the most recent version of NLP Architect available in the master branch. Thanks!
