### ISSUE TITLE
bug: [an error occurred while running Q8BERT]

### ISSUE THREAD

**Issue by Shinonome233** [IntelLabs/nlp-architect#195]
hello, I come from #157. When I run the nlp-train for Q8BERT on MRPC benchmark, an error occurred. The code is like this

`/.local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.`
`File "/home/anaconda3/lib/python3.7/site-packages/nlp_architect/models/transformers/base_model.py", line 409, in update_best_model`
    `if i == 0 and f1 > best_dev:  # dev set`
`TypeError: '>' not supported between instances of 'NoneType' and 'int'`

Could you please tell me whether this is a bug and how can I solve it. If so, could you fix it soon?

Thanks very much.

**Comment by peteriz** [comment]
Hi @Shinonome233 , are you using the latest version of NLP Architect from the master branch?

**Comment by Shinonome233** [comment]
> Hi @Shinonome233 , are you using the latest version of NLP Architect from the master branch?

I am using the version 0.5.5, since there is another error when I try to use 0.5.5.1, like
`OSError: Couldn't reach server to download pretrained model configuration file`

**Comment by rmovva** [comment]
This error still seems to be occurring, even when using the latest version from master.
