### ISSUE TITLE
bug: [In ABSA Opinion lixicon and Aspect lexicon are not being written to a csv when you run train.py]

### ISSUE THREAD

**Issue by AravindR7** [IntelLabs/nlp-architect#196]
**Describe the bug**
In Unsupervised ABSA when you train the model on unsuructured data in csv file, it just prints the aspects and lexicons in the command prompt(As given in source code it just prints aspects and lexicons, code for it to be writing to a csv file is not present). But it should be copied to aspect.csv and opinion.csv in order to run the inference on the new data.

**To Reproduce**
1. https://intellabs.github.io/nlp-architect/absa.html in the documentation, it says run -  python3 examples/absa/train.py --data=TRAINING_DATASET but it should be - python3 examples/absa/train/train.py --data=TRAINING_DATASET(but thats not the issue here)
2. You can see the output on the command prompt 
3.  But the output needs to be written  to the aspect.csv and opinion.csv

**Expected behavior**
When examples/absa/train/train.py is executed it should download the GloVe embeddings for first time and then the output needs to be written to csv in order to run inference on test data.

**Environment setup: **
 - OS (Linux/)
 - Python version: 3.8

**Comment by danielkorat** [comment]
Hi @AravindR7 
Thanks for reporting this issue, I'm looking into it and will update soon.

**Comment by danielkorat** [comment]
Hi @AravindR7 
That doc page is outdated.
Please follow the instructions in the README:
https://github.com/IntelLabs/nlp-architect/blob/master/solutions/absa_solution/README.md

**Comment by AravindR7** [comment]
Hi @danielkorat 
I error I was talking about was from https://github.com/IntelLabs/nlp-architect/tree/master/examples/absa  page: https://github.com/IntelLabs/nlp-architect/tree/master/examples/absa have updated the link on top.

**Comment by danielkorat** [comment]
The aspect and opinion lexicons are written to `~/nlp-architect/cache/absa/train/lexicons/` . 
They were printed to the screen as well. I have now removed those prints, and corrected the output path in the docs.
