### ISSUE TITLE
bug: Couldn't reach server for bert-base-uncased model URL

### ISSUE THREAD

**Issue by rmovva** [IntelLabs/nlp-architect#211]
On MacOS 64-bit, using the latest version of the repo from master.
Trying to run an nlp-train command (for quantizedBERT) using bert-base-uncased.
Getting the following URL error:

`OSError: Couldn't reach server at 'https://d2zs9tzlek599f.cloudfront.net//models/transformers/bert-base-uncased.json' to download pretrained model configuration file.`

**Comment by peteriz** [comment]
Fixed. Thanks for reporting. 
(the issue was double `//` in the URL)
